### ISSUE TITLE
its not center

### ISSUE THREAD

**Issue by l3est** [mdhiggins/CenterTaskbar#1]
I tried this tool, icons aren't centered. they move to right side of taskbar

**Comment by mdhiggins** [comment]
Can you post a screenshot?

Also please include DPI settings, resolution, and windows version

**Comment by l3est** [comment]
there is a big empty space on the left side:
![image](https://user-images.githubusercontent.com/8002505/52522633-26907600-2c9d-11e9-83e0-da6d1216173c.png)
Windows 10 x64
1600x900

**Comment by l3est** [comment]
can you add an option so it only calculate the empty space on taskbar? (not include the clock and other stuff)

**Comment by mdhiggins** [comment]
So that is screen centered as it’s supposed to be. Just because you have additional toolbar items the empty space is not centered but that’s never been the desired effect. It could be done but would require modifying the centering algorithm. I’m not doing much active development on this but you’re welcome to fork it and change things around.

**Comment by l3est** [comment]
it's not just toolbar. it ignores the icons around the clock.
how can i find that area size to reduce it in algorithm? I don't know enough about this.

**Comment by mdhiggins** [comment]
The current algorithm aims to center it on the screen which looks the most natural unless you have significant asymmetry of the toolbar like you do.

If you change the bar size calculation it should give you the results you're after

Try changing it on line 313 to 

`double barSize = horizontal ? tasklistBounds.Width : tasklistBounds.Height;`
