### ISSUE TITLE
Resolution change bug

### ISSUE THREAD

**Issue by VNRARA** [mdhiggins/CenterTaskbar#17]
Program doesn't refresh after resolution changes forcing the user to do a manual scan of screen to re-center the icons.

**Comment by mdhiggins** [comment]
Open to a pull request but not in active development for new features

**Comment by VNRARA** [comment]
It's a bug man not a feature request. Smh 
The icons are off-set to center after resolution changes.

**Comment by mdhiggins** [comment]
You were requesting a feature to add `SystemEvents.DisplaySettingsChanging` event monitoring. The functionality was all there you just wanted to automate screen/resolution changes instead of having to click the scan for screens button. Either way this should be added with latest release

**Comment by VNRARA** [comment]
It is common practice to include this "feature" because any change in resolution makes the icons offset when in fact you'd want it to be constantly in the middle. It's probably 3 lines of code lol: 

if/when SystemEvents.DisplaySettingsChanging { 
function ScanScreenOrWhatEver 

}

**Comment by mdhiggins** [comment]
It's literally already done

**Comment by mdhiggins** [comment]
Gonna lock this since the issue has been addressed with the feature added to the latest release and you continue to be argumentative. If a feature is so simple to add then submit a pull request and prove it. It's a free open source project that is shared at no gain or benefit to myself or contributors and this sort of behavior certainly does not want to make me continue any development on it.
