### ISSUE TITLE
Publish the app to Microsoft Store

### ISSUE THREAD

**Issue by Kenya-West** [mdhiggins/CenterTaskbar#2]
Microsoft Store is one place for everything in your life, moving your experience to a safe one and making it accessible from many devices that added to your Microsoft account.

Publishing apps to Microsoft Store is benefit both for users and developers + enterprise. Deploying classic apps, that available in Microsoft Store, with safe methods to a verified environments is trusted by enterprises and users. From the other hand, developer can benefit from "In-App Purchase" (paid features of the app), making its own Insider programs, setting up subscriptions and advertisements.

Microsoft corporation has opened a door to developers of classic apps, the way to publish your app to Microsoft Store. UWP brings a second life for your apps: notifications, full power of trusted UWP/WinRT API, easy debug, easy deploy, additional features.

Learn more about that easy process [here](https://developer.microsoft.com/windows/bridges/desktop).

Best regards,
Innokenty Ivanov,
North-Eastern Federal University student (PhD student).
Programmer, web developer, **Microsoft Student Partner**.
My [e-mail](mailto:Kenya-West@outlook.com).

**Comment by acseven** [comment]
Or instead contribute to Microsoft's Powertoys! 
https://github.com/microsoft/PowerToys/issues/503

**Comment by myusrn** [comment]
Wrt to publishing this very useful tsr in the microsoft store i had a system tray / notification area based keyboard shortcuts utility i created that i also wanted to publish in the store to make it easier for non technical people to discover and try, see [a few windows niceties](https://www.microsoft.com/en-us/p/a-few-windows-niceties/9mtw4cj7s276?activetab=pivot%3Aoverviewtab) and associated https://github.com/myusrn/uwpSystrayExtension sources.  

The sample that i found from a msft uwp app & store publishing evangelist outlining how to do that using desktop bridge services, i.e. a uwp wrapper app that just launches a winforms hidden window app with trusted system access rights, was https://stefanwick.com/2017/06/24/uwp-app-with-systray-extension/.  

The gotcha is with the store app distribution i couldn't find a way to enable system tray / notification area winform process to have registry permissions, for hkcu\Software\Microsoft\Windows\CurrentVersion\Run, and a store app shortcut, needed to enable/disable run at windows signin like you can do with win32 apps.  That said it appears the proper way to enable a store app to automatically start at signin is simply placing it in the user's %appdata%\Microsoft\Windows\Start Menu\Programs\Startup folder, e.g. search "[run microsoft store apps at startup](https://bing.com/search?q=run+microsoft+store+apps+at+startup)" -> [https://tenforums.com/tutorials/104440-run-microsoft-store-apps-startup-windows-10-a.html](https://tenforums.com/tutorials/104440-run-microsoft-store-apps-startup-windows-10-a.html) where win+r[run] | shell:appsfolder allows access to installed store apps in order to create shortcuts to them in legacy programs menu system.

**Comment by ghost** [comment]
This is not a UWP app so, as @myusrn mentioned there are a number of wonky steps that would need to be taken to force this to be possible. I like the idea of this being a feature of PowerToys @acseven but unfortunately it looks like PowerToys is a C++ app and this is a C# app. Someone would need to port the code over to C++ before you could submit a PR to Microsoft.
