### ISSUE TITLE
didn't work

### ISSUE THREAD

**Issue by jacobax** [mdhiggins/CenterTaskbar#21]
run the program, and nothing happen nothing changes, run as admin or not
v1.5, windows 10 20H2
![屏幕截图 2020-10-29 144832](https://user-images.githubusercontent.com/23228895/97535342-79bcd600-19f6-11eb-8c65-98292c71d655.png)

**Comment by mdhiggins** [comment]
The network monitor you have installed can break this. Try turning that off

**Comment by mdhiggins** [comment]
I also just updated to 20H2 and it hasn't created an problems

**Comment by jacobax** [comment]
> I also just updated to 20H2 and it hasn't created an problems

thanks it works!
any way to run the network monitor as well?

**Comment by mdhiggins** [comment]
I haven’t been able to figure it out. 

It doesn’t seem to be everyone who’s affected cause I was able to start the network monitor without issue but other users have had problems. The network monitor adds itself to the taskbar in kind of a weird way that seems to cause issue in some cases.

Try using the network monitor without the search box enabled since that’s what I use on my setup. Also make sure the network monitor and center app are being launched by the same user account.

**Comment by jacobax** [comment]
> I haven’t been able to figure it out. It doesn’t seem to be everyone who’s affected cause I was able to start the network monitor without issue but other users have had problems. The network monitor adds itself to the taskbar in kind of a weird way that seems to cause issue in some cases. Try using the network monitor without the search box enabled since that’s what I use on my setup. Also make sure the network monitor and center app are being launched by the same user account.
> […](#)
> Sent from my iPhone
> On Oct 29, 2020, at 3:48 PM, gabou ***@***.***> wrote: ﻿ I also just updated to 20H2 and it hasn't created an problems thanks it works! any way to run the network monitor as well? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jacobax** [comment]
still not working with searchbox closed. thanks any way! keep great work
