### ISSUE TITLE
It doesn't centre if you make the task bar too high

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [mdhiggins/CenterTaskbar#22]
How to reproduce:

unlock task bar
drag it up to about 40% of your screen height
run the program
it will remain on the left always

**Comment by mdhiggins** [comment]
![image](https://user-images.githubusercontent.com/3608298/101166040-a2dc1200-3605-11eb-8384-67d2e3361f0b.png)

Unable to reproduce, also why would anyone ever do this

**Comment by asdsadsaasd12312132** [comment]
https://streamable.com/ospdbz

As for why:
1. ergonomics; putting items and text too low on the screen causes a tendency to tilt the head down, which causes neck strain if sustained for hours
2. speed; it's faster to access the task bar when it's higher up than at the bottom

**Comment by mdhiggins** [comment]
Can you try updating to the latest release?

**Comment by asdsadsaasd12312132** [comment]
It isn't fixed. https://streamable.com/9d5d5s

I spoke with another [developer ](https://github.com/ChrisAnd1998/TaskbarX/issues/478) and he explained the caused as "If the taskbar(s) height goes over 200px then TaskbarX thinks the taskbar is vertical."

**Comment by asdsadsaasd12312132** [comment]
I accidentally closed the issue. It should be open.

**Comment by mdhiggins** [comment]
So the assumption from taskbarX dev is incorrect, the taskbar vertical check, at least in my script which I think TBX borrowed, compares the width and height which should be fine here and I ran the numbers, it is

```
var horizontal = trayBounds.Width > trayBounds.Height;
```

What actually looks like the issue is is that the UI scale calculation is failing. This was kind of a sneaky calculation I came up with because the certain UI elements report a scaled height and others do not, so by comparing the two values the scale could be calculated on a per-monitor basis. The issue here is that its comparing the height of an individual icon and the taskbar, which gets progressively worse the higher you drag the taskbar (icon height stays constant, container goes up and up).

I can instead use the top and left positions instead of height and get around this shortcoming I think and in my tests it seems to be working

b947e2fcce8b0435b85f4478d724ffe8aad10938

That should fix it

https://github.com/mdhiggins/CenterTaskbar/releases/tag/1.7

Let me know

I can't speak to the techniques TBX uses for scale calculation but I know it was an issue that I had solved early on and had passed the technique to that developer so it likely uses the same method and fails for the same reason

**Comment by mdhiggins** [comment]
Hm looks like the calculation isn't perfect, I'll need to mess around a bit more

**Comment by asdsadsaasd12312132** [comment]
It isn't perfect but works sufficiently well. As seen, it isn't fully centred (the line is the centre).
![image](https://user-images.githubusercontent.com/51249734/101237806-cb602b00-372f-11eb-89a8-bc6852b0f912.png)

**Comment by mdhiggins** [comment]
I'll explore some other options to see if I can calculate the UI scale more accurately

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/CenterTaskbar/releases/tag/1.7b

Alternate solution, seems like a more perfect calculation now

783a8faa0b1f54aa71952b6bdb5e3039a1b5d7de

**Comment by asdsadsaasd12312132** [comment]
It looks identical to version 1.7a with imperfect centering to me. https://imgur.com/a/cQ8AKfN

**Comment by mdhiggins** [comment]
Is the centering perfect when it's not stretched out?

**Comment by asdsadsaasd12312132** [comment]
No. It's slightly to the left.
![Screenshot_2](https://user-images.githubusercontent.com/51249734/101262461-0ba4c500-3793-11eb-8ea1-fcd1b645c596.png)

**Comment by mdhiggins** [comment]
Found a couple little issues with padding that appears to have been added in later windows versions so I added some calculations to monitor for that in the future
Its a bitch to get it to scale with DPI but think I got it about as accurate as I can

https://github.com/mdhiggins/CenterTaskbar/releases/tag/1.8

See if that's better

**Comment by asdsadsaasd12312132** [comment]
Yes. It's perfect.
